### ISSUE TITLE
Feature Request: Show Mac icons for cmd/opt/shift

### ISSUE THREAD

**Issue by markmarino** [romanhaa/ubersicht-shortcut-widget#1]
This would be super cool if it could display the Mac keyboard icons/glyphs for Cmd/Ctrl/Opt/Shift instead of having them shown in text format.  That would make the widget very slick.  Is there any way to do that?

**Comment by romanhaa** [comment]
Have you tried using Unicode characters in the file defining the shortcuts?

- ⌘ Command (or Cmd)
- ⇧ Shift
- ⌥ Option (or Alt)
- ⌃ Control (or Ctrl)

I haven't tried it myself but that might just work.

**Comment by markmarino** [comment]
Yes, it does seem to work, thanks!
